version: "3"

services:

  urlfrontier:
    user: root
    image: crawlercommons/url-frontier:2.3.1
    command: -s 9100 rocksdb.path=/storage/rocksdb
    ports:
    - "7071:7071"
    - "9100:9100"   
    volumes:
      - urlfrontier-storage:/storage

volumes:
  urlfrontier-storage:
